### ISSUE TITLE
SUMMARY: Satisfactory

### ISSUE THREAD

**Issue by jzhu01** [devynlyn/prj-rev-bwfs-dasmoto#5]
Neat work on this project! I really liked your usage of spans, and how you chose to handle the h2s. In terms of improvement, I recommend removing the font-weight:bold on your h1 and h2s.

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the fantastic work! ^_^

**Comment by devynlyn** [comment]
Thank you so much for the feedback! Noted about h1 and h2's- now it makes sense that they didn't seem to change after I added that bit of code. xD 

That link about grid-view web design is awesome, thank you! Haha, a bit confusing but I'm definitely up for the challenge. thank you again! ^_^
